# Generated by Django 5.2 on 2025-04-05 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CompanyData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("pdf_file", models.FileField(upload_to="company_data/")),
                ("data", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="RFPDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("pdf_file", models.FileField(upload_to="rfps/")),
                ("content", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="EligibilityResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("result", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "rfp_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rfp_analysis.rfpdocument",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContractRiskResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("result", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "rfp_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rfp_analysis.rfpdocument",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ComplianceResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("result", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "rfp_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rfp_analysis.rfpdocument",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubmissionChecklistResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("result", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "rfp_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rfp_analysis.rfpdocument",
                    ),
                ),
            ],
        ),
    ]
